### ISSUE TITLE
padding in random crop

### ISSUE THREAD

**Issue by SuziKim** [cvpa3/dl-practice#2]
ProcessImageTrain function gets path, rw, rh, rf.
To crop the image, the comment says that we must use rw, rh.
What about padding? Should we just crop from some point randomly or uniformly?

**Comment by SuziKim** [comment]
Oh sorry.
I think the size is fixed as 'cropSize' and we just use rw, rh for padding.
right?

**Comment by cvpa3** [comment]
An image is loaded 36*36 which is supposed to be randomly cropped to 32*32 size.
No padding necessary.

**Comment by SuziKim** [comment]
Gotcha. Thanks!
