### ISSUE TITLE
Questions in estimateInputStat function

### ISSUE THREAD

**Issue by SuziKim** [cvpa3/dl-practice#3]
Three questions in estimateInputStat function

1. What is the purpose of stdEstimate? It looks redundant variable.
2. The comment saids, that we can use getBatchTrain.
As getBatchTrain returns the input which size is different with numIm,
should we repeat to call getBatchTrain to satisfy the count of numIm?
3. meanEstimate is divided by numBatch. Is this because meanEstimate is sum of all mean value of images?

**Comment by cvpa3** [comment]
1.  For pixel std normalization but we do not use that in this practice.
2. Yes, repeat that.
3. Yes we repeated that function numBatch-times.

**Comment by SuziKim** [comment]
Thanks!
