### ISSUE TITLE
Question in Task4 Convergence Speed Test

### ISSUE THREAD

**Issue by SuziKim** [cvpa3/dl-practice#8]
I wonder whether there's some missing in last script:
#CUDA_VISIBLE_DEVICES=0 th main.lua -task slcls -net cifarNetBatchNorm -learnRate 1e-1;

To avoid the assert, assert( #self.opt.learnRate == #modelSet.params ) @slcls line#155, 
I think the learnRate should be two number concatenated with comma.

**Comment by cvpa3** [comment]
Yes, you are right.
TA.

**Comment by SuziKim** [comment]
Thanks!
